### ISSUE TITLE
possibly fatal typo

### ISSUE THREAD

**Issue by vchong** [neutron-org/mainnet-assets#22]
There's a typo in https://github.com/neutron-org/mainnet-assets/blob/main/upgrades/v1.0.2/README.md.
```
minimum-gas-prices = “0.01untrn,0.005ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9,0.05ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349"
```
instead of
```
minimum-gas-prices = "0.01untrn,0.005ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9,0.05ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349"
```

Specifically, an invalid char `“` instead of `"`. If someone just copies and pastes this into `app.toml` without checking, the node might not start and it might be hard to debug.

**Comment by albertandrejev** [comment]
Thank you. Fixed.
